services:
  php:
    image: hrvl/pdi-php:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    networks:
      - aoc
  phpunit:
    image: hrvl/pdi-phpunit:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phpunit
    networks:
      - aoc
networks:
  aoc:
    driver: bridge
